server:
  port: 8889

spring:
  zipkin:
    enabled: true
    base-url: ${zipkin_url}
    service:
      name: config-server-git
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/brtacer/gitconfig.git"
          default-label: main
          skip-ssl-validation: true
          username: ${java6config}
          password: ${GIT_CONFIG}