server:
  port: 7072

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: java6user
      password: root
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root

jwt:
  secretkey: ${java6secretkey}
  audience: ${java6audience}
  issuer: ${java6issuer}

rabbitmq:
  exchange-auth: auth-exchange
  exchange-user: user-exchange
  registerElasticKey: elastic-key
  queueElastic: register-elastic
  registerKey: register-key
  queueRegister: register-queue